# ~/.bashrc: executed by bash(1) for non-login shells.
#
# See bash(1) for more options
#

#
# If not running interactively, don't do anything
#
case $- in
  *i*) ;;
    *) return;;
esac

#
# Don't put duplicate lines or lines starting with space in the history. See
#
HISTCONTROL=ignoreboth

#
# Append to the history file, don't overwrite it
#
shopt -s histappend

#
# Set history length
#
HISTSIZE=1000
HISTFILESIZE=2000

#
# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
#
shopt -s checkwinsize

#
# Enable the "**" pattern used in a pathname expansion context to match all
# files and zero or more directories and subdirectories.
#
shopt -s globstar

#
# Make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

#
# Set variable identifying the chroot you work in (used in the prompt below)
#
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
  debian_chroot=$(cat /etc/debian_chroot)
fi

#
# Enable color support of ls and also add handy aliases
#
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

#
# Some more ls aliases
#
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

#
# Add an "alert" alias for long running commands.
#
# @example
#
#   sleep 10; alert
#
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

#
# Enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi
