#!/bin/bash

#
# Load the default .profile
#
[[ -s "$HOME/.profile" ]] && source "$HOME/.profile"

#
# If not running interactively, don't do anything
#
[ -z "$PS1" ] && return

#
# Don't put duplicate lines or lines starting with space in the history. See
#
HISTCONTROL=ignoreboth

#
# Append to the history file, don't overwrite it
#
shopt -s histappend

#
# Set history length
#
HISTSIZE=1000
HISTFILESIZE=2000

#
# Check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
#
shopt -s checkwinsize

#
# Enable the "**" pattern used in a pathname expansion context to match all
# files and zero or more directories and subdirectories. NOTE: Requires bash 4
#
shopt -s globstar

#
# Make less more friendly for non-text input files, see lesspipe(1)
#
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

#
# Load alias definitions
#
if [ -f "$HOME/.bash_aliases" ]; then
  source "$HOME/.bash_aliases"
fi

#
# Load completions
#
if [ -f "$HOME/.bash_completion" ]; then
  source "$HOME/.bash_completion"
fi

#
# Set custom prompt
#
PS1='\[\033[49;36m\]\u@\h\[\033[01;34m\] \w \$\[\033[00m\] '

#
# Activate direnv
#
eval "$(direnv hook bash)"
