#!/bin/bash

# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login exists.

#
# Set default editor
#
export EDITOR=nvim

#
# Set default terminal
#
export TERM=xterm-256color

#
# Smart pager
#
export PAGER="less"
export LESS="--no-init --quit-if-one-screen --raw-control-chars"

custom_folder="$HOME/.profile.d"

#
# General utilities
#
source "$custom_folder/utils"
source "$custom_folder/paths"
source "$custom_folder/media"
source "$custom_folder/git"
source "$custom_folder/linuxbrew"

#
# Folder for local bins
#
path_append "$HOME/.local/bin"

#
# Language customizations
#
source "$custom_folder/bash"
source "$custom_folder/js"
source "$custom_folder/latex"
source "$custom_folder/ruby"
