---

- name: Install tmux
  homebrew:
    name: tmux
    state: latest

- name: Install shellcheck
  homebrew:
    name: shellcheck
    state: latest

- name: Install ag
  become: true
  apt:
    name: silversearcher-ag
    state: latest

- name: Install direnv
  become: true
  apt:
    name: direnv
