---

engines:
  bundler-audit:
    enabled: true

  duplication:
    enabled: true

    config:
      languages:
        - ruby

  fixme:
    enabled: true

  markdownlint:
    enabled: true

  shellcheck:
    enabled: true
    include:
      - bootstrap.sh
      - dotfiles/bash_aliases
      - dotfiles/bash_completion
      - dotfiles/bash_profile
      - dotfiles/completion.d/*
      - dotfiles/profile
      - dotfiles/profile.d/*

exclude_paths:
  - dotfiles/completion.d/ruby
