AllCops:
  DisplayCopNames: true

  DisplayStyleGuide: true

  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Style/ModuleFunction:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ExtraSpacing:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Performance/Casecmp:
  Enabled: false
