---

addons:
  apt:
    packages:
      - shellcheck

    sources:
      - debian-sid

branches:
  only:
    - master

bundler_args:

env:
  global:
    - SHELLCHECK_OPTS='-x -e SC1090'

language: ruby

rvm:
  - 2.4.1

sudo: false

before_install:
  - gem update --system 2.6.12

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - bin/overcommit --sign
  - bin/overcommit --run
