# frozen_string_literal: true
source "https://rubygems.org"

gem "rails", "5.0.0.beta2"

gem "sqlite3", "~> 1.3" # DBMS
gem "puma", "~> 2.16" # App server
gem "sass-rails", "~> 5.0" # SCSS stylesheets
gem "uglifier", "~> 2.7" # JavaScript asset compressor
gem "coffee-rails", "~> 4.1" # CoffeeScript assets and views
gem "jquery-rails", "~> 4.1" # JavaScript library
gem "slim-rails", "~> 3.0" # Template engine

group :tools do
  gem "brakeman", "~> 3.1"
  gem "byebug", "~> 8.2"
  gem "capybara", "~> 2.6"
  gem "database_cleaner", "~> 1.5"
  gem "mdl", "0.2.1"
  gem "overcommit", "0.32.0.rc1"
  gem "rspec-rails", "~> 3.1"
  gem "rubocop", "0.37.0"
  gem "scss-lint", "0.38.0"
  gem "slim_lint", "0.7.0"
  gem "spring", "~> 1.6"
  gem "web-console", "~> 3.1"
end
