#!/bin/bash

#
# Downloads all mp3 files linked to by a web page.
#
# @param $2 Target url
#
# @example download_mp3 http://bohemianbetyars.hu/release/stone-soup/
#
function download_mp3 {
  wget "$2" -O - | grep -oh "http[^ ]*.mp3" | wget -i -
}

#
# Converts a video file to a gif using `imagemagick` + `ffmpeg`.
#
# @param $1 Source video
# @param $2 Target gif
#
function video2gif {
  if [ "$#" -ne 2 ]
  then
    echo "Usage: video2gif <input>.mp4 <output>.gif"
    return
  fi

  convert -set delay 10 -layers Optimize "$1" "$2"
}
