---

- name: Install git
  apt:
    name: git
    state: latest

- name: Create global src folder
  file:
    dest: /usr/local/src
    state: directory

- name: Download & extract hub sources
  unarchive:
    src: "{{hub_url}}"
    dest: /usr/local/src
    remote_src: yes

- name: Install hub
  copy:
    src: /usr/local/src/{{hub_folder}}/bin/hub
    dest: /usr/local/bin/
    mode: 0755

- name: Install hub docs
  copy:
    src: "{{item}}"
    dest: /usr/local/share/man/man1/
    mode: 0644
  with_fileglob:
    - /usr/local/src/{{hub_folder}}/share/man/man1/*.1
