#!/bin/bash

#
# Alias hub to git
#
eval "$(hub alias -s)"

#
# Review every commit on a branch, oldest to newest
#
function pr_review {
  revisions=$(git log master..HEAD --pretty=format:%h ; echo)
  revisions=$(echo "$revisions" | tac)
  revisions=($revisions)

  git show "${revisions[@]}"
}

#
# Edit all files with merge conflicts
#
function edit_conflicts {
  top_level=$(git rev-parse --show-toplevel)

  files=$(git diff --name-only --diff-filter=U)
  files=($files)

  (cd "$top_level" && nvim "${files[@]}")
}
