#!/bin/bash

#
# Alias hub to git
#
eval "$(hub alias -s)"

#
# Review every commit on a branch, oldest to newest
#
function pr_review {
  revisions=$(git log origin/master...HEAD --pretty=format:%h ; echo)
  mapfile -t revisions <<< "$revisions"

  git show "${revisions[@]}"
}

#
# Adds a trailing new line to every non-binary non-vendored file tracked by git
#
function normalize_new_lines {
  for file in $(git grep --cached -Il '' | grep -v /vendor/)
  do
    if [ -n "$(tail -c 1 < "$file")" ]
    then
      echo >> "$file"
    fi
  done
}

#
# Finds all different file extensions on a project
#
function project_extensions {
  git ls-tree -r HEAD --name-only | perl -ne 'print "*.$1" if m/[^^\/]\.([^.\/]+)$/' | sort -u
}
