#!/bin/bash

export PATH="$PATH:/usr/local/texlive/2015/bin/x86_64-linux"
export MANPATH="$PATH:/usr/local/texlive/2015/texmf-dist/doc/man"
export INFOPATH="$INFOPATH:/usr/local/texlive/2015/texmf-dist/doc/info"
