#!/bin/bash

#
# Appends to PATH without duplicates
#
function PATH_append {
  path_append "$1" "PATH"
}

#
# Appends to MANPATH without duplicates
#
function MANPATH_append {
  path_append "$1" "MANPATH"

  MANPATH_keep_configuration_file_list
}

#
# Appends to INFOPATH without duplicates
#
function INFOPATH_append {
  path_append "$1" "INFOPATH"
}

#
# Prepends to PATH without duplicates
#
function PATH_prepend {
  path_prepend "$1" "PATH"
}

#
# Prepends to MANPATH without duplicates
#
function MANPATH_prepend {
  path_prepend "$1" "MANPATH"

  MANPATH_keep_configuration_file_list
}

#
# Prepends to INFOPATH without duplicates
#
function INFOPATH_prepend {
  path_prepend "$1" "INFOPATH"
}

#
# Prepends to XDG_DATA_DIRS without duplicates
#
function XDG_DATA_DIRS_prepend {
  path_prepend "$1" "XDG_DATA_DIRS"
}

#
# Appends a folder to an environment variable made of a list of folders
# separated by colons
#
function path_append {
  if [ -d "$1" ] && [[ ":${!2}:" != *":$1:"* ]]
  then
    export "$2=${!2:+"${!2}:"}$1"
  fi
}

#
# Prepends a folder to an environment variable made of a list of folders
# separated by colons
#
function path_prepend {
  if [[ ":${!2}:" != *":$1:"* ]]
  then
    export "$2=$1${!2:+":${!2}"}"
  fi
}

function MANPATH_keep_configuration_file_list {
  if [[ ! $MANPATH =~ :.* ]]
  then
    export MANPATH=":$MANPATH"
  fi
}
