#!/bin/bash

eval "$(rbenv init -)"

export BUNDLE_PATH=.bundle/gems

#
# JRUBY_OPTS to make jruby startup time acceptable
#

if [[ $JRUBY_OPTS != *--dev* ]]
then
  export JRUBY_OPTS="$JRUBY_OPTS --dev"
fi

if [[ $JRUBY_OPTS != *--debug* ]]
then
  export JRUBY_OPTS="$JRUBY_OPTS --debug"
fi
