#!/bin/bash

chruby_home="$(brew --repo)/opt/chruby/share/chruby"

function enable_chruby {
  # shellcheck disable=SC1090
  source "$chruby_home/chruby.sh"
}

enable_chruby

function enable_auto_chruby {
  # shellcheck disable=SC1090
  source "$chruby_home/auto.sh"
}

enable_auto_chruby

chruby 2.4.2

#
# JRUBY_OPTS to make jruby startup time acceptable
#

if [[ $JRUBY_OPTS != *--dev* ]]
then
  export JRUBY_OPTS="$JRUBY_OPTS --dev"
fi

if [[ $JRUBY_OPTS != *--debug* ]]
then
  export JRUBY_OPTS="$JRUBY_OPTS --debug"
fi
