#!/bin/bash

function enable_chruby {
  # shellcheck disable=SC1091
  source /usr/local/share/chruby/chruby.sh
}

enable_chruby

function enable_auto_chruby {
  # shellcheck disable=SC1091
  source /usr/local/share/chruby/auto.sh
}

enable_auto_chruby

#
# JRUBY_OPTS to make jruby startup time acceptable
#

if [[ $JRUBY_OPTS != *--dev* ]]
then
  export JRUBY_OPTS="$JRUBY_OPTS --dev"
fi

if [[ $JRUBY_OPTS != *--debug* ]]
then
  export JRUBY_OPTS="$JRUBY_OPTS --debug"
fi
