#!/bin/bash

#
# Recursive search and replace method
#
# @param $1 Old string to be replaced
# @param $2 New string to replace it
#
function search_and_replace {
  [ $# -eq 0 ] && { echo "search_and_replace <old> <new>"; return; }

  git grep -Il '' | xargs perl -pi -e "s/$1/$2/g"
}
