#!/bin/bash

#
# Recursive search and replace method
#
# @param $1 Old string to be replaced
# @param $2 New string to replace it
#
function search_and_replace {
  [ $# -eq 0 ] && { echo "search_and_replace <old> <new>"; return; }

  git grep -Il '' | xargs perl -pi -e "s/$1/$2/g"
}

#
# Updates a migration's timestamp. Useful for rebasing when there
# are outdated migrations.
#
# @param $1 Migration timestamp that needs to be brought up to date
#
function update_migration_timestamp {
  local migration

  migration=$(find db/migrate -name "$1_*.rb")

  if [ "$(echo "$migration" | wc -l)" -gt 1 ]
  then
    echo "*** You have several migrations for the same timestamp."
    return 1
  fi

  mv "$migration" "${migration//$1/$(date +%Y%m%d%H%M%S)}"
}
