---

- name: Setup nodejs repo sources
  apt_repository:
    repo: deb https://deb.nodesource.com/node_8.x xenial main
    state: present

- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
    state: latest

- name: Upgrade npm
  npm:
    name: npm
    global: yes
    state: latest

- name: Install stylelint
  npm:
    name: stylelint
    global: yes
    state: latest

- name: Install eslint
  npm:
    name: eslint
    global: yes
    state: latest
