---

- name: Setup repo sources
  apt_repository:
    filename: docker
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Setup apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Install
  apt:
    name: docker-ce
    state: latest

- name: Startup
  service:
    name: docker
    state: started

- name: Add group
  group:
    name: docker
    state: present

- name: Configure for non-root usage (requires manual re-login)
  user:
    name: "{{lookup('env', 'USER')}}"
    groups: docker
    append: yes

- name: Download docker-compose
  get_url:
    url: "{{compose_url}}"
    force: yes
    dest: /usr/local/bin/docker-compose-{{compose_version}}
    mode: 0755

- name: Symlink docker-compose to latest version
  file:
    src: /usr/local/bin/docker-compose-{{compose_version}}
    dest: /usr/local/bin/docker-compose
    state: link
