---

- name: Setup neovim repo sources
  become: true
  apt_repository: repo='ppa:neovim-ppa/stable' codename=xenial state=present

- name: Install neovim
  become: true
  apt: name=neovim update_cache=yes state=latest

- name: Install python modules prerrequisites
  become: true
  apt: name={{item}} state=latest
  with_items:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip

- name: Install python module
  pip: name=neovim state=latest extra_args='--user'

- name: Install clipboard support
  become: true
  apt: name=xsel state=latest

- name: Create autoload folder
  file: path=~/.config/nvim/autoload state=directory mode=0755

- name: Install vim-plug
  get_url: \
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest=~/.config/nvim/autoload
