---

- name: Ruby dependencies
  become: true
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - build-essential
    - zlib1g-dev
    - libyaml-dev
    - libssl-dev
    - libgdbm-dev
    - libreadline-dev
    - libncurses5-dev
    - libffi-dev

- name: Install ruby-install
  homebrew:
    name: ruby-install
    state: latest

- name: Install chruby
  homebrew:
    name: chruby
    state: latest
